#!/bin/bash
#

CURRENTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function usage() {
   echo "Usage: install_ansible /path/to/ansible.tar"
   echo "    or, set ANSIBLETAR=/path/to/ansible.tar"
}

if ! [ $(id -u) = 0 ]; then
   echo "Error: Must be run as root"
   usage
   exit -1
fi

if [ -f "${CURRENTDIR}/install_ansible.$(hostname -s)" ]; then
    echo "Using ${CURRENTDIR}/install_ansible.$(hostname -s)"
    source ${CURRENTDIR}/install_ansible.$(hostname -s)
fi

if [ $# -ne 1 -a -z "${ANSIBLETAR}" ]; then
    echo "Error: Missing full path to ansible tarball"
    usage
    exit 1
fi

tarball="$1"

if [ ! -z "${ANSIBLETAR}" ]; then
    tarball="${ANSIBLETAR}"
fi

if [ ! -f "${tarball}" ]; then
    echo "Ansible tarball location is invalid: ${tarball}"
    exit 2
fi

tar xf ${tarball} -C /root

ansibledir="/root/$(ls /root | grep -i ansible | grep -v .tar)"
echo "Evaluating ${ansibledir}"
if [ ! -d "${ansibledir}" -o ! -f "${ansibledir}/setup.py" ]; then
    echo "Cannot evaluate extracted ansible location in /root"
    exit 3
fi

echo "Ansible package ${ansibledir}"
cd $ansibledir
python setup.py install
exit $?
