#!/bin/bash
#

CURRENTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! $# -eq 1 ]; then
    echo "Error: Please specify installation environment"
    exit 1
fi

env="$1"

if [ -z "${env}" -o ! -f "${CURRENTDIR}/${env}" -o ! -f "${CURRENTDIR}/${env}.env" ]; then
    echo "Error: Unknown environment ${env}"
    exit 2
fi

source "${CURRENTDIR}/${env}.env"

ansible-playbook ${CURRENTDIR}/playbooks/master.yml \
    -i "${CURRENTDIR}/vagrant"
